---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-client-provisioner-helmchart
  namespace: kube-system
spec:
  chart: stable/nfs-client-provisioner
  targetNamespace: nfs-client-provisioner
  repo: https://kubernetes-charts.storage.googleapis.com
  set:
    nfs.server: 192.168.178.136
    nfs.path: /mnt/nfs_share
    image.repository: quay.io/external_storage/nfs-client-provisioner-arm