---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: lazylibrarian-helmchart
  namespace: kube-system
spec:
  chart: k8s-at-home/lazylibrarian
  targetNamespace: default
  repo: https://k8s-at-home.com/charts/
  set:
    persistence.storageClass: nfs-client
